[[Sundials32]]
arch = "aarch64"
git-tree-sha1 = "010b91b3de8433046a828c2d2fbdcef068d125f6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "ff0a1707772e949160dc2519430b85f842bd4b8fd4a3c97119e7ca0ca1dc9115"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Sundials32]]
arch = "aarch64"
git-tree-sha1 = "e8713f1b5269d8d7dda5f30649274573de24b868"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "afdbf580b560ecb493c6a6230e7dacfd644ccae492b7292947f060f15bbbc1f3"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Sundials32]]
arch = "aarch64"
git-tree-sha1 = "1509f54aae53be1d7ddb7796d18056269855f14f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "f148781030126eaffcff10a568cb90253e83fc7fa6bef759642ba244858238bd"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Sundials32]]
arch = "aarch64"
git-tree-sha1 = "f6b642b4a1e99412d63e52e97f48ffa032ef8f3d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "2ce356313e541d804f84f6b32985ce973573ca9267f6ce8f57b3df289eada2a4"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Sundials32]]
arch = "aarch64"
git-tree-sha1 = "ed2451af0f141dcbc60eccd55c168c643aba651e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "e012dd75b99b03b4ebd3c836c72a4ea0f52348cbfc428a4bb8dc82668adbc18c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Sundials32]]
arch = "aarch64"
git-tree-sha1 = "3fa7da93bc445cc897433547caca32e85ee2dd94"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "cf670b4f57ef932f90c389402461785d052717c372685bd376d2a37463e20b60"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Sundials32]]
arch = "armv7l"
git-tree-sha1 = "1fb0ef26f439f1a1948f6f90b408659f7b40a9ed"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "efa3b96bd69a080bcf0c9dc19b90d632655fd5696dbb2cdc8c1e606e4a43abdf"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Sundials32]]
arch = "armv7l"
git-tree-sha1 = "0ad3c8b4ad59851299062f4f7c69300ae387e8e4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "8bfb08e479bac426b91278f1e980f65834eddee6c2580902d1246580853d1d29"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Sundials32]]
arch = "armv7l"
git-tree-sha1 = "2491f6583f9353749d3175273dc8c0170b5eee8b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "739f2d1c8b0441d4a69cdf71ec3b94f31df3f82ead3bb9f71f213f12ac3dd32c"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Sundials32]]
arch = "armv7l"
git-tree-sha1 = "ed7aaca2b874ff40b994fa713b22fad35bf732b5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "9e8da29136a82483c9c84677a507eb63aff7e604eb72a6d509bac7152144720e"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Sundials32]]
arch = "armv7l"
git-tree-sha1 = "9dcb3f87562503dfe4eba521dbb16e5655c64e54"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "e9ddf7ecb243ea9ff8403f1c50395446490b30a5647cacd0f2f96de7ddfc04ea"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Sundials32]]
arch = "armv7l"
git-tree-sha1 = "ea76ad996f0381278edcec18c54320fb8da7e63d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "7bd3a7235a4fb4d84268e3f29982970b0834675fdbfe61b87d7eac9ed31a67dc"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Sundials32]]
arch = "i686"
git-tree-sha1 = "8b5ff4c3eaf1204071ac049990cdded1c7155bb4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "9869472fb66c906a06fdb912ea05b49276eb442d497ba9485e2f64993d5fedee"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Sundials32]]
arch = "i686"
git-tree-sha1 = "efb97935c2410bb9948ad6defa3d7ff9c28595f0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "a2208c0dc5cb03988a860f0ab061e9e0c3ed1cfa446b93700117dfaa19c899ce"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Sundials32]]
arch = "i686"
git-tree-sha1 = "891597476fca1b516af75617d21e7e9538f02fc4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "45148d28591bdad07b35aa205c849cc51309f32d5f1a36966c01630568391665"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Sundials32]]
arch = "i686"
git-tree-sha1 = "4f01de264aad99578275ffc4eab5f37ba447a76a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "20425c2170c95785bb2339d0ef67af3497d26f8a0fe56c348b2280f7bd5135d3"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.i686-linux-musl-libgfortran3.tar.gz"
[[Sundials32]]
arch = "i686"
git-tree-sha1 = "27433bb25ab45c48a0fdc803abc21230635ced06"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "48c0625205a7d553ddd8d260c9492de73ac96b4c52e69ddde4bb90c7019d42cf"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.i686-linux-musl-libgfortran4.tar.gz"
[[Sundials32]]
arch = "i686"
git-tree-sha1 = "a91ab3775fbd06c75a4b267c1cf1b50cd348e277"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "3085c490abb158f42dcb7022c863599cafe27bb258de33c39f18987b9f267da1"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.i686-linux-musl-libgfortran5.tar.gz"
[[Sundials32]]
arch = "i686"
git-tree-sha1 = "3f41b2ca838645869d150fd4a1be9040364f9d77"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials32.download]]
    sha256 = "fc1a846c92620147c559bbe609f8e2a8f9870644ee57fcdff564a1131ee32f34"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Sundials32]]
arch = "i686"
git-tree-sha1 = "3e3e48a8a88e38c4ae624e1daf8e461fbedfee71"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials32.download]]
    sha256 = "d55a304abf492da8f2fa0ab9ca1116d1d845a83cb095d2cc662b703300f6c687"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Sundials32]]
arch = "i686"
git-tree-sha1 = "210a8caa5598ff0b77fbcd379df0079d4a5ee477"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials32.download]]
    sha256 = "c84b9c9cef23bfe5049796d910b4be9cc8ff20f6db4a8956c3a54933abba1bd7"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "2916b05085467c5f80d519b3dbafb8b3bd6c0971"
libgfortran_version = "3.0.0"
os = "macos"

    [[Sundials32.download]]
    sha256 = "c5d6ad30d2bff174bdb1477a02fdcc6fb3c4376f60f3fabcc806e197578733bb"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "15f032d70907865e36e26509ba7a90b8bf119f15"
libgfortran_version = "4.0.0"
os = "macos"

    [[Sundials32.download]]
    sha256 = "c4b834025eb5b476762759662da98c5079229787cacb87f4336fec76d4f225da"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "d9b99856f483a0004bb114838ac848277fae7c05"
libgfortran_version = "5.0.0"
os = "macos"

    [[Sundials32.download]]
    sha256 = "f958cb965e5ca422f26e80525d5204b99c7280d6c0d1fd3ce46e363637617147"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "3bcffbf67d8a68ac69eeec40d322837a338b8702"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "fb5e9ec90cbd0ec9f82dcb3ccea29a56efb8f8604585a10f22aa17abc27fb470"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "14d438adb9147254dbed898578178bb0bd910c55"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "085538ebf2e81d38b5220eca1f9ece904dffae4623a01ffa1e907777ba9c6249"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "e56fa31cbe537d48b3b8ebb9ab5ceabcae0f1c1b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "036d99ad3a771f3dbe790abeed218aa5f983434e56bb88cf08ee5db35a4f2f92"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "776516aa76aeb565965c1c4468e5612cc153d454"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "a0a2356a195a4e875af2f7897d657731c8eaabd034a405bbfce09c8972798d3f"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "cccfe70eac3120c5c02b809f8b841384cd962b8a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "b83c477f35cbf51c4407354b73cda3d95418897735c21e538e61b1a68e655057"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "8b7cc936cb7cbecd7bf960a607a2fbdbbfb5df2f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Sundials32.download]]
    sha256 = "7de6c9833ba0634dfd82c12ae51d2789d0693adf64b560aca02a726db91c7215"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "f4be768fca99142f4c3f2bdf4f7d926528851214"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Sundials32.download]]
    sha256 = "30c06c677f0c1d48ead59866f3148583b93e2713622fcaeb21672a9abbb4bb71"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "3fa3e66086885fcdfcb4c3a5a8816c7350b88561"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Sundials32.download]]
    sha256 = "96de49b0da3faa793b88770962bc5c0daf1e2eb89e63eeca70b60f20e90878e6"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "cdbf78d7362ec6a8c5ae883c669cc66fa2743c71"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Sundials32.download]]
    sha256 = "6dc86a7a95734dd0fb0da011f57dccc6e25d9339d6ecdb6d52c289cab11bee13"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "a1602c3e02f2496a6d59bacff984cb1cd1e541bf"
libgfortran_version = "3.0.0"
os = "windows"

    [[Sundials32.download]]
    sha256 = "d436655b2fc444c953756758fb494423126044027806a30c31653ef5c63984f8"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "2676d54750aecbf7077179f4238e3f582405a45e"
libgfortran_version = "4.0.0"
os = "windows"

    [[Sundials32.download]]
    sha256 = "11ae01d6c88339447ac81dd69e27e9b520978a0ae019e863c802cd8511eabbe2"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Sundials32]]
arch = "x86_64"
git-tree-sha1 = "38b61df3f4b482cb6f727a2e2ff4cfab4677b5e2"
libgfortran_version = "5.0.0"
os = "windows"

    [[Sundials32.download]]
    sha256 = "94b901b70b0384b123a41befe44a70b74621479e85340d8022f9ef77891d25e2"
    url = "https://github.com/JuliaBinaryWrappers/Sundials32_jll.jl/releases/download/Sundials32-v5.3.0+1/Sundials32.v5.3.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
